
image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

variables:
  POSTGRES_DB: sfs_stack_pg1
  POSTGRES_USER: sfs_stack_usr
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_HOST: db_pg
  DB_NAME: sfs_stack_pg1
  DB_USER: sfs_stack_usr
  DB_PASS: testpassword

before_script:
  - pip install -r requirements.txt
  - ./manage.py wait_for_db
  - ./manage.py makemigrations
  - ./manage.py migrate

stages:
  - Tests

pyre:
  stage: Tests
  script:
    - pyre --search-path "/usr/local/lib/python3.9/site-packages"

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - mkdir /home/app/sfs/apps/theme/static
    - ./manage.py collectstatic --noinput
    - pytest tests/
