
image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

variables:
  POSTGRES_DB: sfs_stack_pg1
  POSTGRES_USER: sfs_stack_usr
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_HOST: db_pg
  DB_NAME: sfs_stack_pg1
  DB_USER: sfs_stack_usr
  DB_PASS: testpassword

before_script:
  - pip install -r requirements.txt
  - ./manage.py wait_for_db
  - ./manage.py makemigrations
  - ./manage.py migrate

stages:
  - Tests
  - Deploy

pyre:
  stage: Tests
  script:
    - pyre --search-path "/usr/local/lib/python3.9/site-packages"

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - ./manage.py collectstatic --noinput
    - pytest tests/

deploy:
  stage: Deploy
  variables:
    SSH_PRIVATE_KEY: "fake key"
    SSH_KNOWN_HOSTS: "i don't know nuthin"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "cd"'
      when: manual
  script:
    - echo $SSH_PRIVATE_KEY #  remove obviously
    - echo $SSH_KNOWN_HOSTS
    - eval $(ssh-agent -s)
    - echo -e "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh asa@sharedfutures.webarch.net
      "echo '=== deploying... ===';
       echo 'just kidding';"
