image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

variables:
  POSTGRES_DB: sfs_stack_pg1
  POSTGRES_USER: sfs_stack_usr
  POSTGRES_PASSWORD: P+!N1*SB:ImVq+0!fGPQC8F  
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - pip install -r requirements.txt

stages:
  - Tests

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - ./manage.py collectstatic
    - pytest tests/
