
image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

variables:
  POSTGRES_DB: sfs_stack_pg1
  POSTGRES_USER: sfs_stack_usr
  POSTGRES_PASSWORD: testpassword
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_HOST: db_pg
  DB_NAME: sfs_stack_pg1
  DB_USER: sfs_stack_usr
  DB_PASS: testpassword

before_script:
  - pip install -r requirements.txt
  - ./manage.py wait_for_db
  - ./manage.py makemigrations
  - ./manage.py migrate

stages:
  - Tests
  - Deploy

pyre:
  stage: Tests
  script:
    - pyre --search-path "/usr/local/lib/python3.9/site-packages"

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - ./manage.py collectstatic --noinput
    - pytest tests/

deploy:
  variables:
    PROD_SERVER_USER: "asa"
    PROD_SERVER_PASS: "wrong password"
  stage: Deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "cd"'
      when: manual
  script:
    - apt-get update
    - apt-get install sshpass
    - sshpass -p $PROD_SERVER_PASS ssh $PROD_SERVER_USER@sharedfutures.webarch.net 'bash -s' <<ENDSSH
    -  whoami
    - ENDSSH
