image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

variables:
  POSTGRES_DB: sfs_stack_pg1
  POSTGRES_USER: sfs_stack_usr
  POSTGRES_PASSWORD: P+!N1*SB:ImVq+0!fGPQC8F  
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_HOST: db_pg
  DB_NAME: sfs_stack_pg1
  DB_USER: sfs_stack_usr
  DB_PASS: P+!N1*SB:ImVq+0!fGPQC8F

before_script:
  - pip install -r requirements.txt
  - find / -name "site-packages"
  - ./manage.py wait_for_db
  - ./manage.py makemigrations
  - ./manage.py migrate

stages:
  - TypeCheck
  - Tests

pyre:
  stage: TypeCheck
  script:
    - pyre --search-path "/home/app/venv/lib/python3.9/site-packages"

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - ./manage.py collectstatic
    - pytest tests/
