image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - Tests

pytest:
  stage: Tests
  script:
    - docker-compose up -d
    - docker-compose exec app "./manage.py collectstatic && pytest tests/"
