image: "python:3.9.5"

before_script:
  - pip install -r requirements.txt
  - manage.py collectstatic

stages:
  - Tests

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - pytest tests/*
