image: python:3.9.5

services:
  - name: postgres:latest
    alias: db_pg

before_script:
  - . app_variable.sh # import variables defined here, conveniently the syntax is also valid sh
  - . db_pg_variables.sh
  - pip install -r requirements.txt
  - ./manage.py wait_for_db
  - ./manage.py makemigrations
  - ./manage.py migrate

stages:
  - Tests

pyre:
  stage: Tests
  script:
    - pyre --search-path "/usr/local/lib/python3.9/site-packages"

pytest:
  stage: Tests
  script:
    - export PYTHONPATH="$PYTHONPATH:."
    - ./manage.py collectstatic
    - pytest tests/
