
version: '3'

services:
  app:
    build:
      context: .
      args:
        USERID: $USER_ID
        GROUPID: $GROUP_ID
    volumes:
      - .:/home/app/sfs
    command: >
        sh -c "python3 manage.py wait_for_db&&
             python3 manage.py makemigrations --no-input &&
             python3 manage.py migrate --no-input &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:9000"

    env_file:
      - variables.env
    depends_on:
      - db_pg

  db_pg:
    image: postgres:12.8-alpine
    env_file:
      - variables.env
    volumes:
      - dbdata:/var/lib/postgres
    restart: always
    ports:
      - "5432:5432"

  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  redis:
    image: redis:6.2.6-alpine
    depends_on:
      - redis-overcommit

  celery:
    restart: always
    build:
      context: .
      args:
        USERID: $USER_ID
        GROUPID: $GROUP_ID
    command: celery -A sfs worker -B -l info
    volumes:
      - .:/home/app/sfs
    depends_on:
      - db_pg
      - redis
      - app

volumes:
  dbdata:
