
version: '3'

services:
  app:
    build:
      context: .
      args:
        USERID: $USER_ID
        GROUPID: $GROUP_ID
    ports:
      - "9000:9000"
    volumes:
      - .:/home/app/sfs
    command: >
        sh -c "python3 manage.py wait_for_db --no-input &&
             python3 manage.py makemigrations --no-input &&
             python3 manage.py migrate --no-input &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:9000"
    env_file:
      - variables.env
    depends_on:
      - db_pg

  db_pg:
    image: postgres:12.8-alpine
    env_file:
      - variables.env
    volumes:
      - /var/lib/postgres
    ports:
      - "127.0.0.1:6432:6432"
    restart: always

  # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

  redis:
    image: redis:6.2.6-alpine
    depends_on:
      - redis-overcommit

  celery:
    restart: always
    build:
      context: .
      args:
        USERID: $USER_ID
        GROUPID: $GROUP_ID
    command: celery -A sfs worker -l info
    volumes:
      - .:/home/app/sfs
    depends_on:
      - db_pg
      - redis
      - app
