---
- hosts: virtualmachines
  become: yes
  tasks:
    # smoke test and git
    - name: ping
      ansible.builtin.ping:
    - name: basics
      ansible.builtin.apt:
        update_cache: yes
        name:
          - vim
          - git
          - postgresql
          - python3.9
          - python3.9-venv
          - python3.9-dev
          - libpq-dev
          - gcc
        state: present

    # node.js and npm
    - name: add nodesource key
      ansible.builtin.apt_key:
        id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
        state: present
    - name: add nodesource repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_16.x nodistro main
    - name: install nodejs
      ansible.builtin.apt:
        update_cache: yes
        name: nodejs
        state: present

    # caddy
    - name: add caddy key
      ansible.builtin.apt_key:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        keyring: /etc/apt/trusted.gpg.d/caddy-stable.gpg
        state: present
    - name: add caddy deb repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy-stable.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - name: add caddy deb-src repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/caddy-stable.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - name: install caddy
      ansible.builtin.apt:
        update_cache: yes
        name: caddy
    - name: caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'

    # deploy user and directory
    - name: www directory
      ansible.builtin.file:
        path: /var/www
        state: directory
        mode: '0755'
    - name: create user
      ansible.builtin.user:
        name: deploy
        password: ""
        shell: /bin/bash
        groups:
          - sudo
          - www-data
        append: yes
        createhome: yes
        skeleton: '/etc/skel'
        generate_ssh_key: yes
        ssh_key_type: 'ed25519'
    - name: www ownership
      ansible.builtin.file:
        path: /var/www
        owner: deploy
        group: www-data
        recurse: yes

    # repository
    - name: clone
      ansible.builtin.git:
        repo: https://github.com/animorphcoop/shared-futures-space
        dest: /var/www/shared-futures-space
        version: setup-ansible
      become_user: deploy
    - name: secrets
      ansible.builtin.template:
        src: secrets.py.j2
        dest: /var/www/shared-futures-space/sfs/settings/secrets.py
        owner: deploy
        group: www-data
        mode: '0664'
      become_user: deploy
    - name: dependencies
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv
        virtualenv: /var/www/shared-futures-space/venv
        requirements: /var/www/shared-futures-space/requirements.txt
      become_user: deploy
    - name: npm
      community.general.npm:
        path: /var/www/shared-futures-space
      become_user: deploy
    - name: build
      ansible.builtin.shell:
        cmd: npm run build
        chdir: /var/www/shared-futures-space
      become_user: deploy

    - name: mkdir uwsgi
      ansible.builtin.file:
        path: /etc/uwsgi
        state: directory
        mode: '0755'
    - name: uwsgi template
      ansible.builtin.template:
        src: sfs.uwsgi.ini.j2
        dest: /etc/uwsgi/sfs.uwsgi.ini
        owner: root
        group: root
        mode: '0644'
    - name: systemd template
      ansible.builtin.template:
        src: sfs.service.j2
        dest: /etc/systemd/system/sfs.service
        owner: root
        group: root
        mode: '0644'
    - name: systemd reload
      ansible.builtin.systemd:
        daemon_reload: true
    - name: systemd enable
      ansible.builtin.systemd:
        name: sfs
        enabled: yes
    - name: systemd start
      ansible.builtin.systemd:
        name: sfs
        state: started
