name: Build

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2.6-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:12.8-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install Node.js Dependencies
      run: npm install
    - name: Build JavaScript
      run: npm run build
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Run Tests
      run: |
        export POSTGRES_HOST=localhost
        export POSTGRES_DB=postgres
        export POSTGRES_USER=postgres
        export POSTGRES_PASSWORD=postgres
        export CELERY_BROKER_URL=redis://redis:6379
        export CELERY_RESULT_BACKEND=redis://redis:6379
        export VITE_DEV_MODE=0
        python manage.py migrate
        python manage.py collectstatic
        pytest tests
